[package]
name = "AppAttempt"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.32.3"
egui = "0.32.1"
egui-file-dialog = "0.11.0"
id3 = "1.16.3"
mp3-duration = "0.1.10"
rodio = "0.21.1"

